### PR TITLE
Avatar component added

### PR DESCRIPTION
**Pull request by rishichourasia**
Created avatar added. Docs site is still in development, so ignore that. creating all components first as of now.

### CODE REVIEW

**Comment by Balakumar3018** [comment]
Avatar looks good
Suggestion - It would be better looking if you give border for avatar box make it like a container.

**Review by sumitch29 — APPROVED** [review]
looks good

**Review by Asuraking1n — COMMENTED** [review]
I guess you should use some right padding bcz texts are very close to right border
And you can increase line height also.

**Review by pnchinmay — APPROVED** [review]
Looks good

**Pull request merged**
