### PR TITLE
Card - Images - Input component added

### PR DESCRIPTION
**Pull request by rishichourasia**
Frontpage and code samples are under work , please ignore that

### CODE REVIEW

**Comment by harshitpaliwal95** [comment]
Links are not working

**Review by sakshi006 — COMMENTED** [review]
Looks good to me. You havent added iframes ?

**Comment by rishichourasia** [comment]
> Links are not working



> it should be working

**Comment by rishichourasia** [comment]
> Looks good to me. You havent added iframes ?

will add today

**Pull request merged**
